version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - npm i && npm uninstall bcrypt && npm i bcrypt && npm run build

artifacts:
  files:
    - "**/*"
